### ISSUE TITLE
Qqqq recall bug

### ISSUE THREAD

**Issue by Petervos2018** [AriaSalvatrice/AriaVCVModules#53] opened 2020-07-23 11:23 UTC
Woof Aria,

This is a bit hard to explain but here I go:
When you load the project I attached, it will play a chord sequence, this should be Cm7 Dm7 E#M7 A#(add9), and it is !
When you stop the clock close rack and start rack again, all is still fine.
But...
...when you close rack while playing (the clock is still running), the first chord in Qqqq will change to the chord that was playing when you closed rack.
So when you close rack while it's playing a Dm7 , the first chord in the seq will become a Dm7.

Greetings Peter.

[AriaBug.zip](https://github.com/AriaSalvatrice/AriaVCVModules/files/4965524/AriaBug.zip)

**Comment by AriaSalvatrice** [comment] 2020-07-23 17:51
The problem here seems to be with the Bogaudio Addr-Seq. It doesn't save its position - when restarting it's always on the first node.

Altering the project to use Seq-3, things work as expected. 

![image](https://user-images.githubusercontent.com/25130242/88320386-cfaa1f80-cd1d-11ea-9a24-4d43b3929bc2.png)

**Comment by AriaSalvatrice** [comment] 2020-07-23 17:56
(Misunderstood the problem, re-opening until I get the time to investigate in detail)

**Comment by AriaSalvatrice** [comment] 2020-07-24 18:04
Got a simpler reproduction working, problem confirmed

**Comment by AriaSalvatrice** [comment] 2020-07-24 22:00
Fixed on the dev branch. Feel free to grab a dev build if you want it fixed ASAP: https://github.com/AriaSalvatrice/AriaVCVModules/releases/tag/AzureCI

**Comment by Petervos2018** [comment] 2020-07-24 22:20
Yep that works 👍 

Thanks.

**Comment by AriaSalvatrice** [comment] 2020-09-03 17:51
There seems to be a regression when using triggers to navigate scenes.

**Comment by Petervos2018** [comment] 2020-09-03 18:12
Did some testing, either I don't know what you mean or I'm doing something wrong...
but I think all is working as it should.
But maybe this is just a placeholder for something you're working on ?
OK Ill butt out now ;)

**Comment by AriaSalvatrice** [comment] 2020-09-04 16:25
Just re-opening this one for my own convenience since I'm pretty sure it's the same bug, don't worry about reproducing it! 

(I think you can unsubscribe if you don't want the issue to ping you anymore)

**Comment by Petervos2018** [comment] 2020-09-04 16:27
Nah I love staying in the loop ;)

**Closed as completed** 2020-10-10 22:31 UTC
Labels: bug
