### ISSUE TITLE
Ext. Rnd for Darius  Feature Request

### ISSUE THREAD

**Issue by Stubs42** [AriaSalvatrice/AriaVCVModules#16] opened 2020-01-27 08:24 UTC
Hi,
I like Darius very much but also love to have the ability to repeat the same semi random sequence multiple times. So I would propose to add an external random cv input to be used in up/down decisions. Added a Screenshot implementing it using cv mapping. In this solution probabilities for up and down have to controlled using Seeds of Change. Would be much easier with an ext. rnd input.
The random generator which allows to set a seed (ext. rnd in) to get repeatable random numbers can easily copied from OrangeLine (Mother) source code. So it shouldn't be much work to do it but would make Darius much more usable in my setups.
![RepeatableDarius](https://user-images.githubusercontent.com/52674858/73159198-40151280-40e6-11ea-8ac9-26d28304bb2c.png)
Regards
Dieter

**Comment by AriaSalvatrice** [comment] 2020-01-27 10:24
Duplicate of #8 - moving conversation there

**Closed as completed by AriaSalvatrice** 2020-01-27 10:24 UTC

**Comment by AriaSalvatrice** [comment] 2020-01-29 10:41
> So it shouldn't be much work to do it but would make Darius much more usable in my setups.

It actually entailed rewriting half the code, to be precise.

Try out the beta! There's a seed input and directional controls.

https://community.vcvrack.com/t/aria-salvatrice-signature-series-1-3-0-beta-2-arcane-atout-aleister-todays-fortune/7734/78
